spring:
  datasource:
    url: jdbc:mysql://localhost:33306/keytree?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234