spring:
  datasource:
    url: jdbc:mysql://localhost:33306/keytree?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 36379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    session:
      tracking-modes: cookie # URL에 JSESSIONID를 노출하지 않음(항상 쿠키를 통해서만 세션 유지)
